#!/bin/bash
STOREPASS="forgotten"
OPENSSL_CONF_TEMPLATE="ssl.cnf.template"

##Criação do Servidor e Clientes para Java.
for name in client1J client2J serverJ; do
	rm -f ${name}.jks ${name}.pem
	echo -e "${name}\nDEI\nISEP\nPORTO\nPORTO\nPT\nyes" | keytool -genkey -v -alias ${name} -keyalg RSA -keysize 2048 \
		-validity 365 -keystore ${name}.jks -storepass ${STOREPASS}
	keytool -exportcert -alias ${name} -keystore ${name}.jks -storepass ${STOREPASS} -rfc -file ${name}.pem
done

##Criação dos Clientes e Servidor para C.
for name in client1 client2 serverC; do
	echo "  ------------ Creating the file with certificate for ${name}    : ${name}.pem"
	echo "  ------------ Creating the file with the private key for ${name}: ${name}.key"
	sed -e s#@NAME@#"$name"# ${OPENSSL_CONF_TEMPLATE} > ssl-tmp.cnf
	openssl req -config ssl-tmp.cnf -new -x509 -days 3650 -nodes -sha256 \
        	-out ${name}.pem -keyout ${name}.key
	rm ssl-tmp.cnf
done

## Criação do ficheiro com os Clientes autenticados.
cat client1.pem client2.pem client1J.pem client2J.pem > authentic-clients.pem

## Aceitação dos certicados por parte do Servidor em Java.
for ENT in client1 client2 client1J client2J; do
	echo "yes"|keytool -import -alias ${ENT} -keystore serverJ.jks -file ${ENT}.pem -storepass ${STOREPASS}
done
for ENT in client1J client2J; do
	echo "yes"|keytool -import -alias serverC -keystore ${ENT}.jks -file serverC.pem -storepass ${STOREPASS}
done
keytool -list -keystore serverJ.jks -storepass ${STOREPASS}

